set(_CATKIN_CURRENT_PACKAGE "detect_degree")
set(detect_degree_VERSION "0.0.0")
set(detect_degree_MAINTAINER "true <true@todo.todo>")
set(detect_degree_PACKAGE_FORMAT "2")
set(detect_degree_BUILD_DEPENDS "cv_bridge" "roscpp" "sensor_msgs" "std_msgs" "image_transport")
set(detect_degree_BUILD_EXPORT_DEPENDS "cv_bridge" "roscpp" "senser_msgs" "std_msgs" "image_transport")
set(detect_degree_BUILDTOOL_DEPENDS "catkin")
set(detect_degree_BUILDTOOL_EXPORT_DEPENDS )
set(detect_degree_EXEC_DEPENDS "cv_bridge" "roscpp" "senser_msgs" "std_msgs" "image_transport")
set(detect_degree_RUN_DEPENDS "cv_bridge" "roscpp" "senser_msgs" "std_msgs" "image_transport")
set(detect_degree_TEST_DEPENDS )
set(detect_degree_DOC_DEPENDS )
set(detect_degree_URL_WEBSITE "")
set(detect_degree_URL_BUGTRACKER "")
set(detect_degree_URL_REPOSITORY "")
set(detect_degree_DEPRECATED "")